version: "3.7"
services:
    server:
        image: mosilink/mosi-server
        build:
            context: ../../../../../
            dockerfile: Dockerfile-server
            args:
                - IMAGE_NAME=mosilink/mosi-server
        env_file: .env
        environment:
            - PL_DATA_BACKEND=postgres
            - PL_DATA_POSTGRES_HOST=pgm-uf620p911pv421vl5o.pg.rds.aliyuncs.com
            - PL_DATA_POSTGRES_PORT=5432
            - PL_DATA_POSTGRES_DATABASE
            - PL_DATA_POSTGRES_USER
            - PL_DATA_POSTGRES_PASSWORD
            - PL_SERVER_CLIENT_URL=https://$PL_HOSTNAME
            - PL_SERVER_REPORT_ERRORS=$PL_ADMIN_EMAIL
            - PL_EMAIL_BACKEND
            - PL_EMAIL_SMTP_HOST
            - PL_EMAIL_SMTP_PORT
            - PL_EMAIL_SMTP_USER
            - PL_EMAIL_SMTP_PASSWORD
            - PL_EMAIL_SMTP_FROM
        expose:
            - 3000
        volumes:
            - attachments:/attachments
        restart: unless-stopped
    pwa:
        env_file: .env
        environment:
            PL_PWA_DIR: /pwa
            PL_SERVER_URL: https://$PL_HOSTNAME/server
            PL_PWA_URL: https://$PL_HOSTNAME
            PL_PWA_PORT: 443
        build:
            context: ../../../../../
            dockerfile: Dockerfile-pwa
            args:
                - IMAGE_NAME=mosilink/mosi-pwa
        volumes:
            - pwa:/pwa
        command: ["build"]
        restart: on-failure
    site:
        environment:
            PL_SITE_DIR: /site
        build:
            context: ../../../../../
            dockerfile: Dockerfile-site
            args:
                - IMAGE_NAME=mosilink/mosi-site
        volumes:
            - site:/site
        command: ["build"]
        restart: on-failure
    nginx:
        env_file: .env
        image: nginx
        depends_on:
            - server
        restart: always
        volumes:
            - pwa:/pwa
            - site:/site
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/$PL_HOSTNAME/fullchain.pem:/tls/cert
            - /etc/letsencrypt/live/$PL_HOSTNAME/privkey.pem:/tls/key
        ports:
            - 80:80
            - 443:443
    certbot:
        env_file: .env
        image: certbot/certbot
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
        command: "certonly --standalone -d $PL_HOSTNAME --expand --non-interactive --agree-tos -m $PL_ADMIN_EMAIL"
        ports:
            - 80:80
            - 443:443
        profiles: ["certbot"]
volumes:
    data:
    attachments:
    pwa:
    site:
