[package]
name = "mosilink"
version = "4.3.0"
description = "mosilink"
authors = [ "mosibitan <mosibitan@163.com>" ]
license = "GPL-3.0"
repository = "https://github.com/mosibitan/mosi"
default-run = "mosilink"
edition = "2021"
build = "src/build.rs"

[build-dependencies.tauri-build]
version = "1.2.1"
features = [ ]

[dependencies.tauri]
version = "1.2.3"
features = [ "updater" ]

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
