FROM node:16-bullseye

ENV PL_SITE_DIR=/site

WORKDIR /padloc

COPY packages/site/package*.json ./packages/site/
COPY packages/site/src ./packages/site/src
COPY packages/site/gulpfile.js ./packages/site/

WORKDIR /padloc/packages/site

RUN npm install

ENTRYPOINT ["npm", "run"]

CMD ["build"]
