FROM node:16-bullseye

ENV PL_SITE_DIR=/site

WORKDIR /padloc

COPY packages/site/package*.json ./packages/site/
COPY packages/site/src ./packages/site/src
COPY packages/site/gulpfile.js ./packages/site/

WORKDIR /padloc/packages/site

RUN npm install
RUN npm run build
RUN mkdir -p /site

RUN cp -r /padloc/packages/site/dist/* /site
