name: Update Dockerhub

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "packages/app/**"
      - "packages/core/**"
      - "packages/locale/**"
      - "assets/**"

jobs:
  update_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (server)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mosibitan/mosi-server:latest
          file: Dockerfile-server

      - name: Build and push Docker image (pwa)
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: mosibitan/mosi-pwa:latest
          file: Dockerfile-pwa

      - name: 安装 SSH 客户端
        run: sudo apt-get install -y openssh-client

      - name: 设置 SSH 密钥
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: 在远程服务器上部署和运行 pwa Docker 镜像
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_HOST << EOF
            sudo docker pull mosi-pwa:latest
            sudo docker stop mosi-pwa || true
            sudo docker rm mosi-pwa || true
            sudo docker run -d \
              -e PL_PWA_DIR='/pwa' \
              -e PL_PWA_PORT='8080' \
              -e PL_PWA_URL='http://120.55.171.238:8080' \
              -e PL_PWA_DISABLE_CSP='true' \
              -e PL_SERVER_URL='http://120.55.171.238:3000' \
              -v pwa:/pwa \
              --restart on-failure \
              --name mosi-pwa \
              -p 8080:8080 \
              mosibitan/mosi-pwa:latest
          EOF

      - name: 在远程服务器上部署和运行 server Docker 镜像
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_HOST << EOF
            sudo docker pull mosi-server:latest
            sudo docker stop mosi-server || true
            sudo docker rm mosi-server || true
            sudo docker run -d \
              -e PL_ADMIN_EMAIL=mosibitan@163.com \
              -e PL_DATA_BACKEND=postgres \
              -e PL_DATA_POSTGRES_HOST=pgm-uf620p911pv421vl.pg.rds.aliyuncs.com \
              -e PL_DATA_POSTGRES_PORT=5432 \
              -e PL_DATA_POSTGRES_USER=yuanxi \
              -e PL_DATA_POSTGRES_PASSWORD=VPV7MB50NJKtFdZgkTdU \
              -e PL_DATA_POSTGRES_DATABASE=mosi \
              -e PL_EMAIL_BACKEND=smtp \
              -e PL_EMAIL_SMTP_HOST=smtp.qq.com \
              -e PL_EMAIL_SMTP_PORT=465 \
              -e PL_EMAIL_SMTP_USER=94176107@qq.com \
              -e PL_EMAIL_SMTP_PASSWORD=dhelpnuhdyoebgjc \
              -e PL_EMAIL_SMTP_FROM="摩斯管理员 <94176107@qq.com>" \
              -e PL_HOSTNAME=120.55.171.238 \
              -e PL_PWA_PORT=8080 \
              -e PL_PWA_DIR=./dist \
              -e PL_PWA_URL=http://120.55.171.238:8080 \
              -e PL_SERVER_CLIENT_URL=http://120.55.171.238:8080 \
              -e PL_SERVER_REPORT_ERRORS=mosibitan@163.com \
              -p 3000:3000 \
              -v attachments:/attachments \
              --restart unless-stopped \
              --name mosi-server \
              mosibitan/mosi-server:latest
          EOF

      - name: 清理 SSH 密钥
        run: rm -rf ~/.ssh
